### ISSUE TITLE
Is the data file missing?

### ISSUE THREAD

**Issue by CanyonWind** [yunjey/show_attend_and_tell#1]
Could you please provide the "data" file via Google drive or any other place where we can download it...

And What's the model you used to train these features?

Thanks.

**Comment by yunjey** [comment]
Thanks for giving a attention.
I am going to provide the data generation code as soon as possible. 
Total data size is more than 150GB.
The code for model is in core/model.py which is reproduced from original theano code.

**Comment by yunjey** [comment]
Thanks for giving a attention.
I am going to provide the data generation code as soon as possible. 
Total data size is more than 150GB.
The code for model is in core/model.py which is reproduced from original theano code.

**Comment by yunjey** [comment]
Now, i updated data genration and preprocessing code.
